spring:
  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: ${spring.rabbitmq.rabbitmq}
                port: ${spring.rabbitmq.port}
                username: ${spring.rabbitmq.username}
                password: ${spring.rabbitmq.password}
      # 消息多个需要在此定义
      function:
        definition: txt2img
      bindings:
        txt2img-out-0:
          binder: defaultRabbit
          destination: txt2img-topic
          content-type: application/json
        txt2img-in-0:
          binder: defaultRabbit
          destination: txt2img-topic
          content-type: text/plain
          group: txt2img-binder-group
          consumer:
            max-attempts: 5

      rabbit:
        bindings:
          txt2img-out-0:
            producer:
              group: txt2img-binder-group
          txt2img-in-0:
            consumer:
              acknowledge-mode: manual # 手动ack消息
              autoBindDlq: true
              dlqTtl: 50000
              dlqDeadLetterExchange: # 默认创建dlq死信交换机
