server:
  port: 30001
spring:
  application:
    name: meta-monitor

  boot:
    admin:
      ui:
        title: @artifactId@-server
      client:
        instance:
          metadata:
            tags:
              environment: local

  security:
    user:
      name: admin
      password: 123456

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
