routes:
  - id: meta-uaa
    uri: lb://meta-uaa
    predicates:
      - Path=/meta-uaa/**
    #filters:
    #  - StripPrefix=1

  - id: meta-admin
    uri: lb://meta-admin
    predicates:
      - Path=/meta-admin/**
      # filters:
      #   - name: RequestRateLimiter
      #     args:
      #       # 限流策略
      #       key-resolver: '#{@remoteAddressKeyResolver}'
      #       # 令牌桶每秒填充率
      #       redis-rate-limiter.burstCapacity: 20
      #       # 令牌桶容量
      #       redis-rate-limiter.replenishRate: 20
      #  - StripPrefix=1

  - id: meta-gen
    uri: lb://meta-gen
    predicates:
      - Path=/meta-gen/**
