server:
  port: 20000
spring:
  application:
    name: @artifactId@

  # 数据源配置
  datasource:
    url: ${meta.datasource.url}
    username: ${meta.datasource.username}
    password: ${meta.datasource.password}
    driver-class-name: ${meta.datasource.driver-class-name}

# spring security安全验证配置白名单
meta:
  security:
    ignoreUrls:
      - "/auth/**"
      - "/oauth/token"
      - "/login/*"
