server:
  port: 20000
spring:
  application:
    name: @artifactId@

  # 数据源配置
  datasource:
    url: ${meta.datasource.url}
    username: ${meta.datasource.username}
    password: ${meta.datasource.password}
    driver-class-name: ${meta.datasource.driver-class-name}

# spring security安全验证配置白名单
meta:
  security:
    ignoreUrls:
      - "/auth/**"
      - "/oauth/token"
      - "/login/*"

  seata:
    application-id: ${spring.application.name}
    tx-service-group: default_tx_group

justauth:
  enabled: true
  cache:
    type: redis
    prefix: 'meta:SOCIAL::STATE::'
  type:
    DOUYIN:
      client-id: awp2r95patxpcplt
      client-secret: 875d99e3696fd32ead691c558086aa71
      redirect-uri: https://localhost/oauth/callback/douyin
    QQ:
      client-id: 101821936
      client-secret: 71bf278fadad9636d6dd0346ff7ee879
      redirect-uri: http://127.0.0.1:88/meta-auth/oauth/callback/qq
      union-id: false
    GITHUB:
      client-id: e230c7a401d897bfb066
      client-secret: e93dced91c104bfe22bbd4e67e5fac59346b0362
      redirect-uri: http://127.0.0.1:88/meta-auth/oauth/callback/github
    GITEE:
      client-id: 7d70b24e879cea1fc9e211defad2a0e41554f944ccd7ed7885a304d480d31d9a
      client-secret: 535246cf9f6df5c9f29d94bfb5f5fd70020f3ae1904c6fcf8a7eb81744358c04
      redirect-uri: http://127.0.0.1:88/meta-auth/oauth/callback/gitee
