spring:
  cloud:
    stream:
      ## 消息多个需要在此定义
      function:
        definition: sms;email;order;user
      bindings:
        user-out-0:
          destination: user-topic
          content-type: application/json
        user-in-0:
          destination: user-topic
          content-type: text/plain
          group: user-binder-group
        sms-out-0:
          destination: sms-topic
          content-type: application/json
        sms-in-0:
          destination: sms-topic
          content-type: text/plain
          group: sms-group
        email-out-0:
          destination: email-topic
          content-type: application/json
        email-in-0:
          destination: email-topic
          content-type: text/plain
          group: email-group
        order-out-0:
          destination: order-topic
          content-type: application/json
        order-in-0:
          destination: order-topic
          content-type: text/plain
          group: order-binder-group
      rocketmq:
        bindings:
          user-out-0:
            producer:
              group: user-binder-group
              sync: true
          user-in-0:
            consumer:
              orderly: true
          sms-out-0:
            producer:
              group: sms-binder-group
              sync: true
          sms-in-0:
            consumer:
              orderly: true
          email-out-0:
            producer:
              group: email-binder-group
              sync: true
          email-in-0:
            consumer:
              orderly: true
          order-out-0:
            producer:
              group: order-binder-group
              transactional: true
          order-in-0:
            consumer:
              orderly: true
