server:
  port: 20001
spring:
  application:
    name: @artifactId@

  # 数据源配置
  datasource:
    url: ${auiu-cloud.datasource.url}
    username: ${auiu-cloud.datasource.username}
    password: ${auiu-cloud.datasource.password}

#provider:
#  application:
#    name: mate-system
#

