server:
  port: 20001
spring:
  application:
    name: @artifactId@

  # 数据源配置
  datasource:
    url: ${auiu-cloud.datasource.url}
    username: ${auiu-cloud.datasource.username}
    password: ${auiu-cloud.datasource.password}

# spring security安全验证配置白名单
auiu-cloud:
  security:
    ignoreUrls:
      - "/auth/**"
      - "/oauth/token"
      - "/login/*"
