version: '3'
services:
  seata-server:
    image: seataio/seata-server                  # 镜像`seataio/seata-server`
    container_name: seata-server                 # 容器名为'seata-server'
    hostname: seata-server                       # 定义主机名
    restart: always                              # 指定容器退出后的重启策略为始终重启
    #容器的映射端口
    ports:
      - "8091:8091"
    volumes:                                    # 数据卷挂载路径设置,将本机目录映射到容器目录
      - ./seata-server/config/registry.conf:/seata-server/resources/registry.conf #左边是本地目录
      - ./seata-server/logs:/root/logs/seata    #日志
    environment:                                # 设置环境变量,相当于docker run命令中的-e
      - SEATA_PORT=8091
      - SEATA_IP=47.100.74.170
      - SEATA_CONFIG_NAME=file:/seata-server/resources/registry.conf  #docker下目录


### 执行推送命令
#  cd /opt/seata/nacos
#  bash nacos-config.sh -h 192.168.1.188 -p 8848 -g SEATA_GROUP -t seata_namespace_id -u nacos -w nacos
