version: "2"
services:
  nacos:
    # 默认使用nacos/nacos-server:v2.1.0
    # m1环境下docker启动失败 使用zhusaidong/nacos-server-m1镜像解决
    image: zhusaidong/nacos-server-m1:2.0.3
    container_name: nacos-standalone-mysql
    env_file:
      - ./env/nacos-standlone-mysql.env
    volumes:
      - ./nacos/logs/:/home/nacos/logs
      - ./nacos/init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
    restart: always
#    depends_on:
#      - mysql

#  mysql:
#    container_name: mysql
#    image: nacos/nacos-mysql:8.0.16
#    env_file:
#      - ./env/mysql.env
#    volumes:
#      - ./mysql:/var/lib/mysql
#    ports:
#      - "33061:3306"
