version: "3"
services:
  nacos:
    # 默认使用nacos/nacos-server:v2.1.1
    # m1环境下docker启动失败 使用nacos/nacos-server:v2.1.1-slim镜像解决
    image: nacos/nacos-server:v2.1.1-slim
    container_name: nacos-standalone-mysql
    env_file:
      - ./env/nacos-standlone-mysql.env
    volumes:
      - ./nacos/logs/:/home/nacos/logs
      - ./nacos/init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
    restart: always
    depends_on:
      - mysql

  mysql:
    container_name: mysql:8.0
    image: mysql:8.0.32
    env_file:
      - ./env/mysql.env
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"

networks:
  meta_net:
    driver: bridge
